services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    restart: always
    networks:
      - nginx-network
  postgres:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    depends_on:
      - nginx
    ports:
      - 5432:5432
    networks:
      - nginx-network
  reservation:
    restart: always
    build:
      context: ./src
      dockerfile: Dockerfile.reservation
    ports:
      - 8081:8080
    depends_on:
      - postgres
      - rabbitmq
      - nginx
    env_file:
      - ./.env
    networks:
      - nginx-network
  paymentinitiator:
    restart: always
    build:
      context: ./src
      dockerfile: Dockerfile.payment
    ports:
      - 8082:8080
    depends_on:
      - postgres
      - rabbitmq
      - nginx
    env_file:
      - ./.env
    networks:
      - nginx-network
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nginx-network
    restart: always
    depends_on:
      - nginx
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
networks:
  nginx-network:
    driver: bridge
