services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
    depends_on:
      - reservation
    networks:
      - nginx-network
  postgres:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: Pa$$w0rd123
    ports:
      - 5432:5432
    networks:
      - nginx-network
  reservation:
    restart: always
    build:
      context: ./HotelBackend.ReservationService/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./.env
    networks:
      - nginx-network
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nginx-network
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
networks:
  nginx-network:
    driver: bridge
